# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 09:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('icon', models.ImageField(upload_to='bange_icon')),
                ('users', models.ManyToManyField(db_table='users_badges', related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
