# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 06:30
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Event name')),
                ('description', models.CharField(max_length=255, verbose_name='Event description')),
                ('location', django.contrib.gis.db.models.fields.PointField(max_length=40, null=True, srid=4326)),
                ('prefered_radius', models.IntegerField(default=1, help_text='in kilometers')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start time')),
                ('pollution_level', models.CharField(choices=[('normal', 'Slightly littered'), ('bad', 'Extremely trashy'), ('extbad', 'Garbocalipse')], default='normal', max_length=6, verbose_name='Pollution level')),
                ('equipment', models.CharField(choices=[('me', 'Me'), ('all', 'Every for himself')], default='all', max_length=6, verbose_name='Who provides equipment ?')),
                ('garbage', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=6, verbose_name='Is the garbage take-out arranged for ?')),
                ('food', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=6, verbose_name='Is food provided?')),
                ('is_cleaned', models.BooleanField(default=False, verbose_name='Cleaned ?')),
                ('collaborators', models.ManyToManyField(blank=True, db_table='event_collaborators', related_name='collaborators', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('image_after', models.ManyToManyField(blank=True, db_table='event_images_after', related_name='After', to='image.Image')),
                ('image_before', models.ManyToManyField(blank=True, db_table='event_images_before', related_name='Before', to='image.Image')),
            ],
        ),
    ]
